"use client";

import Link from "next/link";
import { useState, type ReactNode } from "react";
import { InfoNote } from "@/components/ui/InfoNote";

const tabs = [
  ["inicio", "Cómo funciona"], ["agentes", "Agentes y claves"], ["cliente", "Cliente"], ["cobros", "Cobros"], ["operacion", "Operación"], ["e2e", "Caso completo"], ["produccion", "Producción"],
] as const;
type TabId = (typeof tabs)[number][0];

function Paso({ numero, titulo, children }: { numero: number; titulo: string; children: ReactNode }) {
  return <article className="rounded-xl border border-border bg-surface p-5"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-primary/15 text-sm font-bold text-primary-text">{numero}</span><h3 className="mt-4 font-semibold text-text">{titulo}</h3><div className="mt-1 text-sm leading-6 text-text-muted">{children}</div></article>;
}
function Lista({ children }: { children: ReactNode }) { return <ul className="mt-4 space-y-2 text-sm leading-6 text-text-muted">{children}</ul>; }
function Enlace({ href, titulo, texto }: { href: string; titulo: string; texto: string }) { return <Link href={href} className="rounded-xl border border-border bg-bg p-4 hover:border-primary"><p className="font-medium text-text">{titulo}</p><p className="mt-1 text-sm text-text-muted">{texto}</p></Link>; }

export function DocsContent() {
  const [activeTab, setActiveTab] = useState<TabId>("inicio");
  return <div className="mx-auto max-w-5xl pb-10">
    <header className="rounded-2xl border border-border bg-surface px-6 py-8 sm:px-8"><p className="text-sm font-medium text-secondary">Kaudal Docs</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-text">Tu manual para vender y operar agentes.</h1><p className="mt-3 max-w-3xl text-text-muted">Sigue las pestañas de izquierda a derecha: configuras el servicio, el cliente paga y aporta su clave de IA, y Kaudal controla el estado de cada cuenta.</p></header>
    <div role="tablist" aria-label="Secciones de documentación" className="mt-6 flex gap-1 overflow-x-auto rounded-xl border border-border bg-surface-alt p-1.5">{tabs.map(([id, label]) => <button key={id} type="button" role="tab" aria-selected={activeTab === id} aria-controls={`panel-${id}`} id={`tab-${id}`} onClick={() => setActiveTab(id)} className={`shrink-0 rounded-lg px-4 py-2 text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary ${activeTab === id ? "bg-primary text-primary-text shadow-sm" : "text-text-muted hover:bg-surface hover:text-text"}`}>{label}</button>)}</div>

    {activeTab === "inicio" && <section role="tabpanel" id="panel-inicio" aria-labelledby="tab-inicio" className="mt-6"><InfoNote>Kaudal organiza el servicio y mide su operación. El agente vive en tu workflow, n8n, Mastra o código propio; Kaudal no reemplaza ese motor.</InfoNote><h2 className="mt-8 text-xl font-semibold text-text">El flujo completo</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><Paso numero={1} titulo="Creas el cliente">Registra su empresa y crea su acceso al portal. Cada cliente queda aislado y solo ve sus datos.</Paso><Paso numero={2} titulo="Conectas su agente">Registras el endpoint y token de ingest del agente que ya configuraste. Kaudal recibe su uso y estado.</Paso><Paso numero={3} titulo="El cliente habilita el servicio">Agrega su API key de IA y completa el primer pago de tu suscripción. Ambas condiciones son necesarias.</Paso><Paso numero={4} titulo="Operas y acompañas">Revisas uso, costo, margen, tickets y el estado de la instancia desde el panel.</Paso></div><div className="mt-6 rounded-xl border border-border bg-surface p-5"><h3 className="font-semibold text-text">¿Quién paga qué?</h3><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-lg bg-bg p-4"><p className="font-medium text-text">Cliente → proveedor de IA</p><p className="mt-1 text-sm text-text-muted">Los tokens de OpenAI, Anthropic u otro proveedor, con la key que aporta el cliente.</p></div><div className="rounded-lg bg-bg p-4"><p className="font-medium text-text">Cliente → Kaudal / Flow</p><p className="mt-1 text-sm text-text-muted">Tu plan mensual: infraestructura, gestión, soporte y tu margen.</p></div></div></div></section>}

    {activeTab === "agentes" && <section role="tabpanel" id="panel-agentes" aria-labelledby="tab-agentes" className="mt-6 rounded-xl border border-border bg-surface p-6"><h2 className="text-xl font-semibold text-text">Agentes, endpoints y API keys</h2><p className="mt-2 text-text-muted">Tú preparas el agente. El cliente no necesita aprender n8n ni editar un workflow.</p><ol className="mt-5 list-decimal space-y-3 pl-5 text-sm leading-6 text-text-muted"><li>Entra a <Link className="font-medium text-primary-text hover:underline" href="/agentes/nuevo">Registrar agente</Link>, selecciona al cliente y escribe un nombre entendible.</li><li>Conecta el endpoint y prueba la conexión antes de entregarlo.</li><li>Guarda el token de ingest para que el agente reporte consumo a Kaudal.</li><li>El cliente ingresa su propia API key desde el portal. La interfaz muestra una versión enmascarada.</li></ol><div className="mt-6 rounded-lg border border-info/30 bg-info/10 p-4 text-sm leading-6 text-text-muted"><strong className="text-text">Regla práctica:</strong> la key del cliente paga la IA; tu cobro mensual paga el servicio. Nunca pongas una key en un workflow, captura, chat o repositorio.</div><h3 className="mt-7 font-semibold text-text">Ejemplo</h3><p className="mt-2 text-sm leading-6 text-text-muted">Una clínica contrata un agente de WhatsApp. Tú mantienes el workflow; la clínica agrega su key de Anthropic y paga tu plan. Cuando llega una consulta, el workflow usa la key de la clínica y reporta uso a Kaudal.</p></section>}

    {activeTab === "cliente" && <section role="tabpanel" id="panel-cliente" aria-labelledby="tab-cliente" className="mt-6 rounded-xl border border-border bg-surface p-6"><h2 className="text-xl font-semibold text-text">Qué necesita entregar el cliente</h2><p className="mt-2 text-text-muted">Puedes usar esta lista en la llamada de onboarding. El cliente entrega información de negocio y acceso a su consumo de IA; tú conservas la operación técnica.</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><div className="rounded-xl border border-border bg-bg p-5"><h3 className="font-semibold text-text">Le pides</h3><Lista><li>• Razón social, RUT, giro, contacto y correo.</li><li>• Su API key de Anthropic, OpenAI u otro proveedor.</li><li>• Aprobación del plan mensual y datos de facturación.</li><li>• Acceso o prueba del canal: WhatsApp, formulario o documento.</li></Lista></div><div className="rounded-xl border border-border bg-bg p-5"><h3 className="font-semibold text-text">No le pides ni le muestras</h3><Lista><li>• Contraseñas de Railway, Supabase, Flow o n8n.</li><li>• Tokens de ingest, endpoints internos ni claves técnicas.</li><li>• Workflows, prompts o datos de otro cliente.</li><li>• El costo de tus proveedores internos como si fuera su key de IA.</li></Lista></div></div><h3 className="mt-7 font-semibold text-text">Primera entrega</h3><ol className="mt-4 list-decimal space-y-2 pl-5 text-sm leading-6 text-text-muted"><li>Recibe la invitación, define contraseña y entra al portal.</li><li>Guarda su API key y confirma que aparece enmascarada.</li><li>Completa el primer pago de su plan.</li><li>Tras la confirmación, prueba una conversación o tarea real del agente.</li><li>Revisa Uso y costo, Estado de cuenta y Dudas y reclamos.</li></ol></section>}

    {activeTab === "cobros" && <section role="tabpanel" id="panel-cobros" aria-labelledby="tab-cobros" className="mt-6"><div className="rounded-xl border border-border bg-surface p-6"><h2 className="text-xl font-semibold text-text">Cobros y activación</h2><p className="mt-2 text-text-muted">No actives una instancia dedicada antes del primer pago confirmado: así no absorbes ese costo por clientes que aún no pagan.</p><div className="mt-6 grid gap-4 sm:grid-cols-3"><Paso numero={1} titulo="Plan">Defines un precio que cubra instancia, soporte y margen.</Paso><Paso numero={2} titulo="Pago">El cliente completa el cobro de tu suscripción en Flow.</Paso><Paso numero={3} titulo="Activación">El webhook confirmado habilita el servicio y la instancia.</Paso></div><Lista><li>• Un pago fallido inicia un período de gracia.</li><li>• Si no se regulariza, la instancia se suspende.</li><li>• Al volver a pagar, el servicio puede reactivarse.</li></Lista></div><InfoNote className="mt-6">Actualmente Flow funciona en sandbox: puedes ensayar pagos, gracia y suspensión sin dinero. No hay cargos reales ni activación real de Railway todavía.</InfoNote><Link href="/cobros" className="mt-6 inline-flex rounded-lg border border-border bg-surface px-4 py-2 text-sm font-medium text-text hover:border-primary">Abrir Cobros</Link></section>}

    {activeTab === "operacion" && <section role="tabpanel" id="panel-operacion" aria-labelledby="tab-operacion" className="mt-6 rounded-xl border border-border bg-surface p-6"><h2 className="text-xl font-semibold text-text">Operación diaria</h2><p className="mt-2 text-text-muted">Este es el orden recomendado para revisar el negocio cada semana.</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><Enlace href="/uso" titulo="Uso y costo" texto="Detecta consumo inesperado y clientes sin actividad." /><Enlace href="/instancias" titulo="Instancias" texto="Revisa cobertura, costo mensual y margen." /><Enlace href="/reclamos" titulo="Soporte" texto="Responde tickets y deja trazabilidad." /><Enlace href="/clientes" titulo="Clientes" texto="Confirma acceso, estado y responsable de cada cuenta." /></div><h3 className="mt-7 font-semibold text-text">Antes de entregar un agente</h3><Lista><li>• Prueba el endpoint y una conversación de punta a punta.</li><li>• Comprueba que el agente registra uso con su token de ingest.</li><li>• Confirma una key válida y que el plan está activo.</li><li>• Indica al cliente dónde ver su portal y cómo abrir un ticket.</li></Lista></section>}

    {activeTab === "e2e" && <section role="tabpanel" id="panel-e2e" aria-labelledby="tab-e2e" className="mt-6"><div className="rounded-xl border border-border bg-surface p-6"><p className="text-sm font-medium text-secondary">Caso ejemplo</p><h2 className="mt-1 text-xl font-semibold text-text">Clínica Norte contrata su agente de WhatsApp</h2><p className="mt-2 text-sm leading-6 text-text-muted">Este ejemplo muestra todo lo que ocurre, incluyendo quién paga cada parte. Es el flujo que se validará antes de abrir producción.</p><div className="mt-6 space-y-3"><Paso numero={1} titulo="Tú preparas el servicio">Creas “Clínica Norte”, registras su agente de WhatsApp y pruebas el endpoint en tu ambiente de desarrollo. Aún no levantas una instancia dedicada ni cobras al cliente.</Paso><Paso numero={2} titulo="El cliente entra a su portal">La clínica recibe su acceso, ingresa su API key de Anthropic/OpenAI y acepta tu plan mensual, por ejemplo $99.000 + IVA. La key queda asociada a ese cliente: sus tokens se cobran directamente a su cuenta del proveedor de IA.</Paso><Paso numero={3} titulo="El cliente paga">Flow confirma el pago a Kaudal mediante webhook. En ese instante Kaudal marca la suscripción como activa. En producción, ese evento también creará o despertará la instancia de la clínica.</Paso><Paso numero={4} titulo="El agente trabaja">El cliente escribe por WhatsApp. El workflow responde usando la key del cliente y reporta uso a Kaudal. Tú ves volumen, costo operativo y margen; la clínica ve estado y soporte en su portal.</Paso><Paso numero={5} titulo="Se liquida tu venta">Flow descuenta su comisión y deposita el resto de la venta a la cuenta bancaria que configures como comercio. Con ese dinero pagas Railway/VPS y demás costos; la diferencia es tu margen.</Paso><Paso numero={6} titulo="Si el siguiente cobro falla">Kaudal marca la suscripción como morosa e inicia la gracia. Debe enviar avisos y, si no se regulariza, suspender la instancia. Si el cliente paga, se reactiva. Los avisos por correo y la suspensión real del hosting se conectan al pasar a producción.</Paso></div></div><InfoNote className="mt-6">Con cero caja no conviene prometer activación inmediata: Flow confirma el pago en línea, pero el depósito a tu banco puede llegar el siguiente o tercer día hábil, según tu tarifa. Además Railway/VPS suele requerir un medio de pago tuyo. Parte con una reserva pequeña o usa prepago inicial que cubra ese desfase.</InfoNote></section>}

    {activeTab === "produccion" && <section role="tabpanel" id="panel-produccion" aria-labelledby="tab-produccion" className="mt-6"><div className="rounded-xl border border-warning/30 bg-warning/10 p-6"><h2 className="text-xl font-semibold text-text">Pasar de sandbox a producción</h2><p className="mt-2 text-sm leading-6 text-text-muted">La instalación está preparada para simular el flujo. Para cobrar y desplegar de verdad hay que conectar proveedores con secretos de producción.</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><div className="rounded-xl border border-border bg-surface p-5"><h3 className="font-semibold text-text">Debes tener</h3><Lista><li>• Credenciales comerciales de Flow y webhook firmado.</li><li>• Token de Railway o tu proveedor de infraestructura.</li><li>• Configuración DTE/proveedor tributario, si emitirás documentos.</li><li>• Secretos de Supabase y dominio HTTPS.</li></Lista></div><div className="rounded-xl border border-border bg-surface p-5"><h3 className="font-semibold text-text">Se valida antes de abrir</h3><Lista><li>• Un evento de pago no cobra ni activa dos veces.</li><li>• La instancia se crea solo tras pago confirmado.</li><li>• La suspensión es real al terminar la gracia.</li><li>• Las keys están cifradas, enmascaradas y fuera de logs.</li></Lista></div></div></div><div className="mt-6 rounded-xl border border-border bg-surface p-6"><h2 className="text-xl font-semibold text-text">Correos y recordatorios</h2><p className="mt-2 text-sm leading-6 text-text-muted">El flujo de pagos y estados está simulado, pero el envío de email transaccional todavía no está conectado a un proveedor (Resend, SendGrid, Postmark u otro). Por eso hoy no salen recordatorios reales de pago, gracia o suspensión.</p><Lista><li>• Recordatorio antes del vencimiento.</li><li>• Aviso inmediato de pago confirmado o fallido.</li><li>• Aviso al iniciar y al terminar el período de gracia.</li><li>• Confirmación de reactivación tras regularizar el pago.</li></Lista><p className="mt-4 text-sm text-text-muted">Al conectar producción, estos avisos deben dispararse desde los eventos de cobro y quedar registrados para evitar duplicados.</p></div><p className="mt-6 text-sm leading-6 text-text-muted">No subas keys al repositorio ni las pegues en el chat. Se cargan como secretos del hosting. Primero se prueba todo en sandbox/staging y luego se habilita un cliente real con un plan de bajo costo.</p></section>}
  </div>;
}
